FROM python:2.7

CMD ["python", "manage.py"]
ENV PYTHONUNBUFFERED 1
EXPOSE 8000
WORKDIR /app/web

RUN apt-get update && apt-get install -y \
        mysql-client \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

COPY . /app/web
RUN pip install -r requirements.txt \
     && mkdir -p /app/web/static \
     && pip install -e .

